resources:
  - url: http://10.0.1.20:5000/bom-radar-card.js
    type: module
views:
  - cards:
      - type: custom:bom-radar-card
        name: BOM Radar Card Development
        entity: sun.sun
        test_gui: true
