name: "Build"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          rm -rf /home/runner/work/bom-radar-card/bom-radar-card/node_modules
          npm install
          npm run build

      - name: Zip
        run: |
          rm /home/runner/work/bom-radar-card/bom-radar-card/dist/bom-radar-card.zip
          zip /home/runner/work/bom-radar-card/bom-radar-card/dist/bom-radar-card.zip /home/runner/work/bom-radar-card/bom-radar-card/dist/*
