name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Build
      - name: Build the file
        run: |
          rm -rf /home/runner/work/bom-radar-card/bom-radar-card/node_modules
          cd /home/runner/work/bom-radar-card/bom-radar-card
          npm install
          npm run build

      - name: Zip
        run: |
          pushd /home/runner/work/bom-radar-card/bom-radar-card/dist
          rm -f bom-radar-card.zip
          zip bom-radar-card.zip *
          popd

      # Upload build file to the release as an asset.
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/bom-radar-card/bom-radar-card/dist/bom-radar-card.zip
          asset_name: bom-radar-card.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Cleanup
        run: |
          rm -f /home/runner/work/bom-radar-card/bom-radar-card/dist/bom-radar-card.zip
